import type { Member, Sprint, Project, Task, Page, TaskPriority } from './types'

export const PROJ_PALETTE = ['#4B7BF5','#37A066','#7C5CDE','#E07B2A','#D95050','#0EA5E9','#D946EF','#F59E0B','#10B981','#6366F1']
export const MEMBER_COLORS = ['#4B7BF5','#37A066','#7C5CDE','#E07B2A','#D95050','#0EA5E9','#F59E0B','#10B981']
export const ROLES = ['Tech Lead','Backend Dev','Frontend Dev','Fullstack Dev','Mobile Dev','QA Engineer','DevOps','Data Engineer','Product Manager','Designer','Scrum Master']

export const PRIORITY_ORDER: Record<TaskPriority, number> = {
  crítica: 0, alta: 1, média: 2, baixa: 3,
}

export const NAV_ITEMS: { icon: string; label: string; page: Page }[] = [
  { icon: '⬛', label: 'Visão Geral', page: 'overview' },
  { icon: '▦', label: 'Projetos', page: 'projects' },
  { icon: '◫', label: 'Sprints', page: 'sprints' },
  { icon: '☰', label: 'Backlog', page: 'backlog' },
  { icon: '◎', label: 'Equipe', page: 'team' },
  { icon: '↗', label: 'Relatórios', page: 'reports' },
]

export const INIT_MEMBERS: Member[] = [
  { id: 'm1', name: 'Carlos Mendes', avatar: 'CM', color: '#4B7BF5', role: 'Tech Lead', tasks: { total: 6, done: 2, delayed: 3, blocked: 1 }, projects: ['Portal do Cliente B2B'], workload: 92, email: 'carlos.mendes@empresa.com' },
  { id: 'm2', name: 'Beatriz Souza', avatar: 'BS', color: '#37A066', role: 'Backend Dev', tasks: { total: 5, done: 3, delayed: 1, blocked: 0 }, projects: ['Plataforma de Pagamentos'], workload: 78, email: 'beatriz.souza@empresa.com' },
  { id: 'm3', name: 'Priya Singh', avatar: 'PS', color: '#7C5CDE', role: 'Frontend Dev', tasks: { total: 7, done: 3, delayed: 2, blocked: 0 }, projects: ['Portal do Cliente B2B'], workload: 85, email: 'priya.singh@empresa.com' },
  { id: 'm4', name: 'Ana Lima', avatar: 'AL', color: '#4B7BF5', role: 'Fullstack Dev', tasks: { total: 8, done: 5, delayed: 1, blocked: 0 }, projects: ['Portal do Cliente B2B','ERP Interno'], workload: 70, email: 'ana.lima@empresa.com' },
  { id: 'm5', name: 'Tiago Alves', avatar: 'TA', color: '#E07B2A', role: 'Backend Dev', tasks: { total: 5, done: 2, delayed: 2, blocked: 0 }, projects: ['Plataforma de Pagamentos'], workload: 80, email: 'tiago.alves@empresa.com' },
  { id: 'm6', name: 'Marcos Ferreira', avatar: 'MF', color: '#37A066', role: 'QA Engineer', tasks: { total: 4, done: 3, delayed: 0, blocked: 0 }, projects: ['Plataforma de Pagamentos'], workload: 55, email: 'marcos.ferreira@empresa.com' },
  { id: 'm7', name: 'Juliana Park', avatar: 'JP', color: '#D95050', role: 'Frontend Dev', tasks: { total: 4, done: 2, delayed: 1, blocked: 0 }, projects: ['ERP Interno'], workload: 62, email: 'juliana.park@empresa.com' },
  { id: 'm8', name: 'Rafael Costa', avatar: 'RC', color: '#7C5CDE', role: 'DevOps', tasks: { total: 3, done: 1, delayed: 1, blocked: 1 }, projects: ['Portal do Cliente B2B'], workload: 88, email: 'rafael.costa@empresa.com' },
]

export const INIT_SPRINTS: Sprint[] = [
  { id: 1, name: 'Sprint 14', project: 'Portal do Cliente B2B', startDate: '2026-07-14', endDate: '2026-07-25', daysDelayed: 11, progress: 58, totalTasks: 24, doneTasks: 14, blockedTasks: 3, team: ['Ana Lima','Carlos Mendes','Priya Singh','Rafael Costa'], goal: 'Finalizar SSO, onboarding redesign e dashboard de métricas.' },
  { id: 2, name: 'Sprint 9', project: 'Plataforma de Pagamentos', startDate: '2026-07-21', endDate: '2026-08-01', daysDelayed: 4, progress: 72, totalTasks: 18, doneTasks: 13, blockedTasks: 1, team: ['Beatriz Souza','Marcos Ferreira','Tiago Alves'], goal: 'Testes de carga, webhook de recusa e integração Pagar.me sandbox.' },
  { id: 3, name: 'Sprint 6', project: 'ERP Interno', startDate: '2026-07-28', endDate: '2026-08-04', daysDelayed: 1, progress: 85, totalTasks: 12, doneTasks: 10, blockedTasks: 0, team: ['Ana Lima','Juliana Park'], goal: 'Exportação PDF e relatório de folha de pagamento.' },
]

export const INIT_PROJECTS: Project[] = [
  { id: 'p1', name: 'Portal do Cliente B2B', color: '#4B7BF5', description: 'Portal self-service para clientes corporativos com SSO, dashboards e gestão de contratos.', status: 'em andamento', startDate: '2026-05-01', endDate: '2026-09-30', progress: 52, sprints: { total: 16, done: 9, active: 1, delayed: 1 }, tasks: { total: 98, done: 51, delayed: 14, blocked: 3, cancelled: 5 }, team: ['Ana Lima','Carlos Mendes','Priya Singh','Rafael Costa'], risks: ['Dependência de integração com AD do cliente','Escopo de relatórios crescendo sem controle'], milestones: [{ name: 'Alpha interno', date: '2026-07-15', done: true },{ name: 'Beta clientes selecionados', date: '2026-08-20', done: false },{ name: 'Go-live', date: '2026-09-30', done: false }] },
  { id: 'p2', name: 'Plataforma de Pagamentos', color: '#37A066', description: 'API de pagamentos com suporte a múltiplos gateways, webhooks e conciliação automática.', status: 'em andamento', startDate: '2026-06-10', endDate: '2026-10-15', progress: 68, sprints: { total: 12, done: 7, active: 1, delayed: 1 }, tasks: { total: 72, done: 49, delayed: 6, blocked: 1, cancelled: 3 }, team: ['Beatriz Souza','Marcos Ferreira','Tiago Alves'], risks: ['Certificação PCI-DSS pendente','Gateway principal com instabilidade em homologação'], milestones: [{ name: 'Integração Stripe', date: '2026-07-01', done: true },{ name: 'Integração Pagar.me', date: '2026-08-10', done: false },{ name: 'Certificação PCI', date: '2026-09-15', done: false },{ name: 'Go-live', date: '2026-10-15', done: false }] },
  { id: 'p3', name: 'ERP Interno', color: '#7C5CDE', description: 'Módulos de RH, financeiro e relatórios para uso interno. Substituição do legado em Access.', status: 'em andamento', startDate: '2026-04-01', endDate: '2026-08-31', progress: 84, sprints: { total: 10, done: 8, active: 1, delayed: 1 }, tasks: { total: 55, done: 46, delayed: 4, blocked: 0, cancelled: 2 }, team: ['Ana Lima','Juliana Park'], risks: ['Migração de dados do Access com inconsistências históricas'], milestones: [{ name: 'Módulo RH', date: '2026-06-01', done: true },{ name: 'Módulo Financeiro', date: '2026-07-20', done: true },{ name: 'Módulo Relatórios', date: '2026-08-15', done: false },{ name: 'Go-live geral', date: '2026-08-31', done: false }] },
]

export const INIT_TASKS: Task[] = [
  { id: 'T-2201', title: 'Integração SSO com Active Directory', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Carlos Mendes', avatar: 'CM', avatarColor: '#4B7BF5', priority: 'crítica', status: 'bloqueada', daysDelayed: 11, plannedEnd: '2026-07-25', estimatedHours: 40, blockedBy: 'Credenciais do AD não fornecidas pelo cliente', tags: ['backend','segurança'] },
  { id: 'T-2195', title: 'Redesign do fluxo de onboarding', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Priya Singh', avatar: 'PS', avatarColor: '#7C5CDE', priority: 'alta', status: 'em andamento', daysDelayed: 7, plannedEnd: '2026-07-25', estimatedHours: 24, blockedBy: null, tags: ['frontend','UX'] },
  { id: 'T-2209', title: 'Dashboard de métricas em tempo real', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Ana Lima', avatar: 'AL', avatarColor: '#4B7BF5', priority: 'alta', status: 'em andamento', daysDelayed: 2, plannedEnd: '2026-07-25', estimatedHours: 32, blockedBy: null, tags: ['frontend','dados'] },
  { id: 'T-2210', title: 'Configuração de permissões por perfil', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Carlos Mendes', avatar: 'CM', avatarColor: '#4B7BF5', priority: 'alta', status: 'em andamento', daysDelayed: 0, plannedEnd: '2026-07-25', estimatedHours: 16, blockedBy: null, tags: ['backend'] },
  { id: 'T-2211', title: 'Deploy em ambiente de staging', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Rafael Costa', avatar: 'RC', avatarColor: '#7C5CDE', priority: 'alta', status: 'bloqueada', daysDelayed: 5, plannedEnd: '2026-07-25', estimatedHours: 8, blockedBy: 'Ambiente cloud sem cota de CPU aprovada', tags: ['devops'] },
  { id: 'T-2212', title: 'Testes de regressão — módulo contratos', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Priya Singh', avatar: 'PS', avatarColor: '#7C5CDE', priority: 'média', status: 'planejada', daysDelayed: 0, plannedEnd: '2026-07-25', estimatedHours: 12, blockedBy: null, tags: ['QA'] },
  { id: 'T-2213', title: 'Exportação de contratos em PDF', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Ana Lima', avatar: 'AL', avatarColor: '#4B7BF5', priority: 'média', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-07-22', estimatedHours: 10, blockedBy: null, tags: ['frontend'] },
  { id: 'T-2214', title: 'Notificação por e-mail de vencimento', project: 'Portal do Cliente B2B', sprint: 'Sprint 14', assignee: 'Carlos Mendes', avatar: 'CM', avatarColor: '#4B7BF5', priority: 'baixa', status: 'cancelada', daysDelayed: 0, plannedEnd: '2026-07-25', estimatedHours: 6, blockedBy: null, tags: ['backend'] },
  { id: 'T-2180', title: 'Autenticação 2FA via TOTP', project: 'Portal do Cliente B2B', sprint: 'Sprint 13', assignee: 'Carlos Mendes', avatar: 'CM', avatarColor: '#4B7BF5', priority: 'alta', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-07-11', estimatedHours: 20, blockedBy: null, tags: ['backend','segurança'] },
  { id: 'T-2181', title: 'Listagem paginada de contratos', project: 'Portal do Cliente B2B', sprint: 'Sprint 13', assignee: 'Priya Singh', avatar: 'PS', avatarColor: '#7C5CDE', priority: 'alta', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-07-11', estimatedHours: 14, blockedBy: null, tags: ['frontend'] },
  { id: 'T-2187', title: 'Testes de carga na rota /checkout', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Beatriz Souza', avatar: 'BS', avatarColor: '#37A066', priority: 'alta', status: 'em andamento', daysDelayed: 8, plannedEnd: '2026-08-01', estimatedHours: 20, blockedBy: null, tags: ['QA','performance'] },
  { id: 'T-2163', title: 'Webhook de pagamento recusado', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Tiago Alves', avatar: 'TA', avatarColor: '#E07B2A', priority: 'média', status: 'em andamento', daysDelayed: 5, plannedEnd: '2026-08-01', estimatedHours: 16, blockedBy: null, tags: ['backend'] },
  { id: 'T-2190', title: 'Conciliação automática diária', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Beatriz Souza', avatar: 'BS', avatarColor: '#37A066', priority: 'alta', status: 'em andamento', daysDelayed: 0, plannedEnd: '2026-08-01', estimatedHours: 28, blockedBy: null, tags: ['backend','dados'] },
  { id: 'T-2191', title: 'Integração Pagar.me sandbox', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Tiago Alves', avatar: 'TA', avatarColor: '#E07B2A', priority: 'alta', status: 'planejada', daysDelayed: 0, plannedEnd: '2026-08-01', estimatedHours: 24, blockedBy: null, tags: ['backend','integração'] },
  { id: 'T-2192', title: 'Relatório de chargebacks', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Marcos Ferreira', avatar: 'MF', avatarColor: '#37A066', priority: 'média', status: 'revisão', daysDelayed: 0, plannedEnd: '2026-08-01', estimatedHours: 10, blockedBy: null, tags: ['QA'] },
  { id: 'T-2193', title: 'Dashboard de transações tempo real', project: 'Plataforma de Pagamentos', sprint: 'Sprint 9', assignee: 'Beatriz Souza', avatar: 'BS', avatarColor: '#37A066', priority: 'média', status: 'cancelada', daysDelayed: 0, plannedEnd: '2026-08-01', estimatedHours: 18, blockedBy: null, tags: ['frontend'] },
  { id: 'T-2170', title: 'Integração gateway Stripe', project: 'Plataforma de Pagamentos', sprint: 'Sprint 8', assignee: 'Tiago Alves', avatar: 'TA', avatarColor: '#E07B2A', priority: 'crítica', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-07-18', estimatedHours: 32, blockedBy: null, tags: ['backend','integração'] },
  { id: 'T-2171', title: 'Modelo de dados de transações', project: 'Plataforma de Pagamentos', sprint: 'Sprint 8', assignee: 'Beatriz Souza', avatar: 'BS', avatarColor: '#37A066', priority: 'alta', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-07-18', estimatedHours: 14, blockedBy: null, tags: ['backend'] },
  { id: 'T-2178', title: 'Exportação de relatório em PDF', project: 'ERP Interno', sprint: 'Sprint 6', assignee: 'Juliana Park', avatar: 'JP', avatarColor: '#D95050', priority: 'média', status: 'revisão', daysDelayed: 3, plannedEnd: '2026-08-04', estimatedHours: 16, blockedBy: null, tags: ['frontend'] },
  { id: 'T-2220', title: 'Relatório de folha de pagamento', project: 'ERP Interno', sprint: 'Sprint 6', assignee: 'Ana Lima', avatar: 'AL', avatarColor: '#4B7BF5', priority: 'alta', status: 'em andamento', daysDelayed: 0, plannedEnd: '2026-08-04', estimatedHours: 20, blockedBy: null, tags: ['backend','dados'] },
  { id: 'T-2221', title: 'Gráfico de horas por departamento', project: 'ERP Interno', sprint: 'Sprint 6', assignee: 'Juliana Park', avatar: 'JP', avatarColor: '#D95050', priority: 'média', status: 'planejada', daysDelayed: 0, plannedEnd: '2026-08-04', estimatedHours: 12, blockedBy: null, tags: ['frontend','dados'] },
  { id: 'T-2222', title: 'Migração dados financeiros legado', project: 'ERP Interno', sprint: 'Sprint 6', assignee: 'Ana Lima', avatar: 'AL', avatarColor: '#4B7BF5', priority: 'crítica', status: 'concluída', daysDelayed: 0, plannedEnd: '2026-08-01', estimatedHours: 40, blockedBy: null, tags: ['dados','migração'] },
  { id: 'T-2223', title: 'Aprovação de férias via workflow', project: 'ERP Interno', sprint: 'Sprint 6', assignee: 'Juliana Park', avatar: 'JP', avatarColor: '#D95050', priority: 'baixa', status: 'cancelada', daysDelayed: 0, plannedEnd: '2026-08-04', estimatedHours: 8, blockedBy: null, tags: ['backend'] },
]
